---

- name: "17.1.1 | PATCH | Ensure Audit Credential Validation is set to Success and Failure"
  when: win11cis_rule_17_1_1
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_17.1.1
    - credential_validation
    - NIST800-171_3.3.1
    - NIST800-171_3.3.2
    - NIST800-171_3.3.6
    - NIST800-53R5_AU-12
    - NIST800-53R5_AU-3
    - NIST800-53R5_AU-3_1
    - NIST800-53R5_AU-7
  block:
    - name: "17.1.1 | AUDIT | Ensure Audit Credential Validation is set to Success and Failure | Get current audit events"
      ansible.windows.win_shell: AuditPol /get /subcategory:"Credential Validation" -r | ConvertFrom-Csv | Select-Object -expand "Inclusion Setting"
      changed_when: false
      check_mode: false
      failed_when: false
      register: discovered_17_1_1_audit

    - name: "17.1.1 | PATCH | Ensure Audit Credential Validation is set to Success and Failure | Success"
      when: "'Success' not in discovered_17_1_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Credential Validation" /success:enable

    - name: "17.1.1 | PATCH | Ensure Audit Credential Validation is set to Success and Failure | Failure"
      when: "'Failure' not in discovered_17_1_1_audit.stdout"
      ansible.windows.win_shell: AuditPol /set /subcategory:"Credential Validation" /failure:enable
