---

- name: "18.9.5.1 | PATCH | Ensure Turn On Virtualization Based Security is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
      name: EnableVirtualizationBasedSecurity
      data: 1
      type: dword
  when: win11cis_rule_18_9_5_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.1
      - virtualization_based_security

- name: "18.9.5.2 | PATCH | Ensure 'Turn On Virtualization Based Security: Select Platform Security Level' is set to 'Secure Boot' or higher"
  block:
      - name: "18.9.5.2 | PATCH | Ensure 'Turn On Virtualization Based Security: Select Platform Security Level' is set to 'Secure Boot' or higher | Set Variable."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
            name: RequirePlatformSecurityFeatures
            data: "{{ win11cis_virtualization_based_security_level }}"
            type: dword
        when: win11cis_virtualization_based_security_level == 1 or win11cis_virtualization_based_security_level == 3

      - name: "18.9.5.2 | AUDIT | Ensure 'Turn On Virtualization Based Security: Select Platform Security Level' is set to 'Secure Boot' or higher | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid setting for win11cis_virtualization_based_security_level. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win11cis_virtualization_based_security_level != 1
            - win11cis_virtualization_based_security_level != 3

      - name: "18.9.5.2 | AUDIT | Ensure 'Turn On Virtualization Based Security: Select Platform Security Level' is set to 'Secure Boot' or higher | Warn Count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '18.9.5.2'
        when:
            - win11cis_virtualization_based_security_level != 1
            - win11cis_virtualization_based_security_level != 3
  when: win11cis_rule_18_9_5_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.2
      - virtualization_based_security

- name: "18.9.5.3 | PATCH | Ensure Turn On Virtualization Based Security Virtualization Based Protection of Code Integrity is set to Enabled with UEFI lock"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
      name: HypervisorEnforcedCodeIntegrity
      data: 1
      type: dword
  when: win11cis_rule_18_9_5_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.3
      - virtualization_based_security

- name: "18.9.5.4 | PATCH | Ensure Turn On Virtualization Based Security Require UEFI Memory Attributes Table is set to True checked"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
      name: HVCIMATRequired
      data: 1
      type: dword
  when: win11cis_rule_18_9_5_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.4
      - virtualization_based_security

- name: "18.9.5.5 | PATCH | Ensure Turn On Virtualization Based Security Credential Guard Configuration is set to Enabled with UEFI lock"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
      name: LsaCfgFlags
      data: 1
      type: dword
  when: win11cis_rule_18_9_5_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.5
      - virtualization_based_security

- name: "18.9.5.6 | PATCH | Ensure Turn On Virtualization Based Security Secure Launch Configuration is set to Enabled"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
      name: ConfigureSystemGuardLaunch
      data: 1
      type: dword
  when: win11cis_rule_18_9_5_6
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.6
      - virtualization_based_security

- name: "18.9.5.7 | PATCH | Ensure 'Turn On Virtualization Based Security: Kernel-mode Hardware-enforced Stack Protection' is set to 'Enabled: Enabled in enforcement mode'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
      name: ConfigureKernelShadowStacksLaunch
      data: 1
      type: dword
  when: win11cis_rule_18_9_5_7
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.9.5.7
      - virtualization_based_security
