---

- name: "5.34 | PATCH | Ensure 'Windows Event Collector (Wecsvc)' is set to 'Disabled'."
  when: win11cis_rule_5_34
  tags:
    - level2-high-security-sensitive-data-environment
    - patch
    - automated
    - rule_5.34
    - wecsvc
  block:
    - name: "5.34 | AUDIT | Ensure 'Windows Event Collector (Wecsvc)' is set to 'Disabled'. | Check to see if Wecsvc service exists."
      ansible.windows.win_service_info:
        name: Wecsvc
      register: discovered_5_34_wecsvc_service_info

    - name: "5.34 | PATCH | Ensure 'Windows Event Collector (Wecsvc)' is set to 'Disabled'. | Disable Wecsvc service."
      when: discovered_5_34_wecsvc_service_info.exists
      ansible.windows.win_service:
        name: Wecsvc
        start_mode: disabled
        state: stopped

- name: "5.35 | PATCH | Ensure 'Windows Media Player Network Sharing Service (WMPNetworkSvc)' is set to 'Disabled' or 'Not Installed'."
  when: win11cis_rule_5_35
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.35
    - wmpnetworksvc
  block:
    - name: "5.35 | AUDIT | Ensure 'Windows Media Player Network Sharing Service (WMPNetworkSvc)' is set to 'Disabled' or 'Not Installed'. | Check to see if WMPNetworkSvc service exists."
      ansible.windows.win_service_info:
        name: WMPNetworkSvc
      register: discovered_5_35_wmpnetworksvc_service_info

    - name: "5.35 | PATCH | Ensure 'Windows Media Player Network Sharing Service (WMPNetworkSvc)' is set to 'Disabled' or 'Not Installed'. | Disable WMPNetworkSvc service."
      when:
        - discovered_5_35_wmpnetworksvc_service_info.exists
        - not win11cis_uninstall_wmpnetworksvc_service
      ansible.windows.win_service:
        name: WMPNetworkSvc
        start_mode: disabled
        state: stopped

    - name: "5.35 | PATCH | Ensure 'Windows Media Player Network Sharing Service (WMPNetworkSvc)' is set to 'Disabled' or 'Not Installed'. | Uninstall WMPNetworkSvc service."
      when:
        - discovered_5_35_wmpnetworksvc_service_info.exists
        - win11cis_uninstall_wmpnetworksvc_service
      ansible.windows.win_service:
        name: WMPNetworkSvc
        state: absent

- name: "5.36 | PATCH | Ensure 'Windows Mobile Hotspot Service (icssvc)' is set to 'Disabled'."
  when: win11cis_rule_5_36
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.36
    - icssvc
  block:
    - name: "5.36 | AUDIT | Ensure 'Windows Mobile Hotspot Service (icssvc)' is set to 'Disabled' | Check to see if icssvc service exists."
      ansible.windows.win_service_info:
        name: icssvc
      register: discovered_5_36_icssvc_service_info

    - name: "5.36 | PATCH | Ensure 'Windows Mobile Hotspot Service (icssvc)' is set to 'Disabled' | Disable icssvc service."
      when: discovered_5_36_icssvc_service_info.exists
      ansible.windows.win_service:
        name: icssvc
        start_mode: disabled
        state: stopped

- name: "5.37 | PATCH | Ensure 'Windows Push Notifications System Service (WpnService)' is set to 'Disabled'."
  when: win11cis_rule_5_37
  tags:
    - level2-high-security-sensitive-data-environment
    - patch
    - automated
    - rule_5.37
    - wpnservice
  block:
    - name: "5.37 | AUDIT | Ensure 'Windows Push Notifications System Service (WpnService)' is set to 'Disabled' | Check to see if WpnService service exists."
      ansible.windows.win_service_info:
        name: WpnService
      register: discovered_5_37_wpnservice_service_info

    - name: "5.37 | PATCH | Ensure 'Windows Push Notifications System Service (WpnService)' is set to 'Disabled' | Disable WpnService service."
      when: discovered_5_37_wpnservice_service_info.exists
      ansible.windows.win_service:
        name: WpnService
        start_mode: disabled
        state: stopped

- name: "5.38 | PATCH | Ensure 'Windows PushToInstall Service (PushToInstall)' is set to 'Disabled'."
  when: win11cis_rule_5_38
  tags:
    - level2-high-security-sensitive-data-environment
    - patch
    - automated
    - rule_5.38
    - pushtoinstall
  block:
    - name: "5.38 | AUDIT | Ensure 'Windows PushToInstall Service (PushToInstall)' is set to 'Disabled' | Check to see if PushToInstall service exists."
      ansible.windows.win_service_info:
        name: PushToInstall
      register: discovered_5_38_pushtoinstall_service_info

    - name: "5.38 | PATCH | Ensure 'Windows PushToInstall Service (PushToInstall)' is set to 'Disabled' | Disable PushToInstall service."
      when: discovered_5_38_pushtoinstall_service_info.exists
      ansible.windows.win_service:
        name: PushToInstall
        start_mode: disabled
        state: stopped

- name: "5.39 | PATCH | Ensure 'Windows Remote Management (WS-Management) (WinRM)' is set to 'Disabled'."
  when:
    - win11cis_rule_5_39
    - not win_skip_for_test
  tags:
    - level2-high-security-sensitive-data-environment
    - patch
    - automated
    - rule_5.39
    - winrm
  block:
    - name: "5.39 | AUDIT | Ensure 'Windows Remote Management (WS-Management) (WinRM)' is set to 'Disabled' | Check to see if WinRM service exists."
      ansible.windows.win_service_info:
        name: WinRM
      register: discovered_5_39_winrm_service_info

    - name: "5.39 | PATCH | Ensure 'Windows Remote Management (WS-Management) (WinRM)' is set to 'Disabled' | Disable WinRM service."
      when: discovered_5_39_winrm_service_info.exists
      ansible.windows.win_service:
        name: WinRM
        start_mode: disabled
        state: stopped

- name: "5.40 | PATCH | Ensure 'World Wide Web Publishing Service (W3SVC)' is set to 'Disabled' or 'Not Installed."
  when: win11cis_rule_5_40
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.40
    - w3svc
  block:
    - name: "5.40 | AUDIT | Ensure 'World Wide Web Publishing Service (W3SVC)' is set to 'Disabled' or 'Not Installed | Check to see if W3SVC service exists."
      ansible.windows.win_service_info:
        name: W3SVC
      register: discovered_5_40_w3svc_service_info

    - name: "5.40 | PATCH | Ensure 'World Wide Web Publishing Service (W3SVC)' is set to 'Disabled' or 'Not Installed | Disable W3SVC service."
      when:
        - discovered_5_40_w3svc_service_info.exists
        - not win11cis_uninstall_w3svc_service
      ansible.windows.win_service:
        name: W3SVC
        start_mode: disabled
        state: stopped

    - name: "5.40 | PATCH | Ensure 'World Wide Web Publishing Service (W3SVC)' is set to 'Disabled' or 'Not Installed | Uninstall W3SVC service."
      when:
        - discovered_5_40_w3svc_service_info.exists
        - win11cis_uninstall_w3svc_service
      ansible.windows.win_service:
        name: W3SVC
        state: absent

- name: "5.41 | PATCH | Ensure 'Xbox Accessory Management Service (XboxGipSvc)' is set to 'Disabled'"
  when: win11cis_rule_5_41
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.41
    - xboxgipsvc
  block:
    - name: "5.41 | AUDIT | Ensure 'Xbox Accessory Management Service (XboxGipSvc)' is set to 'Disabled' | Check to see if XboxGipSvc service exists."
      ansible.windows.win_service_info:
        name: XboxGipSvc
      register: discovered_5_41_xboxgipsvc_service_info

    - name: "5.41 | PATCH | Ensure 'Xbox Accessory Management Service (XboxGipSvc)' is set to 'Disabled' | Disable XboxGipSvc service."
      when: discovered_5_41_xboxgipsvc_service_info.exists
      ansible.windows.win_service:
        name: XboxGipSvc
        start_mode: disabled
        state: stopped

- name: "5.42 | PATCH | Ensure 'Xbox Live Auth Manager (XblAuthManager)' is set to 'Disabled'"
  when: win11cis_rule_5_42
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.42
    - xblauthmanager
  block:
    - name: "5.42 | AUDIT | Ensure 'Xbox Live Auth Manager (XblAuthManager)' is set to 'Disabled' | Check to see if XblAuthManager service exists."
      ansible.windows.win_service_info:
        name: XblAuthManager
      register: discovered_5_42_xblauthmanager_service_info

    - name: "5.42 | PATCH | Ensure 'Xbox Live Auth Manager (XblAuthManager)' is set to 'Disabled' | Disable XblAuthManager service."
      when: discovered_5_42_xblauthmanager_service_info.exists
      ansible.windows.win_service:
        name: XblAuthManager
        start_mode: disabled
        state: stopped

- name: "5.43 | PATCH | Ensure 'Xbox Live Game Save (XblGameSave)' is set to 'Disabled'"
  when: win11cis_rule_5_43
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.43
    - xblgamesave
  block:
    - name: "5.43 | AUDIT | Ensure 'Xbox Live Game Save (XblGameSave)' is set to 'Disabled' | Check to see if XblGameSave service exists."
      ansible.windows.win_service_info:
        name: XblGameSave
      register: discovered_5_43_xblgamesave_service_info

    - name: "5.43 | PATCH | Ensure 'Xbox Live Game Save (XblGameSave)' is set to 'Disabled' | Disable XblGameSave service."
      when: discovered_5_43_xblgamesave_service_info.exists
      ansible.windows.win_service:
        name: XblGameSave
        start_mode: disabled
        state: stopped

- name: "5.44 | PATCH | Ensure 'Xbox Live Networking Service (XboxNetApiSvc)' is set to 'Disabled'"
  when: win11cis_rule_5_44
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_5.44
    - xboxnetapisvc
  block:
    - name: "5.44 | AUDIT | Ensure 'Xbox Live Networking Service (XboxNetApiSvc)' is set to 'Disabled' | Check to see if XboxNetApiSvc service exists."
      ansible.windows.win_service_info:
        name: XboxNetApiSvc
      register: discovered_5_44_xboxnetapisvc_service_info

    - name: "5.44 | PATCH | Ensure 'Xbox Live Networking Service (XboxNetApiSvc)' is set to 'Disabled' | Disable XboxNetApiSvc service."
      when: discovered_5_44_xboxnetapisvc_service_info.exists
      ansible.windows.win_service:
        name: XboxNetApiSvc
        start_mode: disabled
        state: stopped
