---

- name: "18.8.2 | PATCH | Ensure Remove Personalized Website Recommendations from the Recommended section in the Start Menu is set to Enabled"
  when: win11cis_rule_18_8_2
  tags:
    - level2-high-security-sensitive-data-environment
    - patch
    - automated
    - rule_18.8.2
    - start_menu
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer
    name: HideRecommendedPersonalizedSites
    data: 1
    type: dword
