---

- name: "SECTION | 18.8.1 | Notifications"
  tags:
    - administrative_templates_computer
    - start_menu_and_taskbar
    - notifications
  ansible.builtin.import_tasks:
    file: cis_18.8.1.x.yml

- name: "SECTION | 18.8 | Start Menu and Taskbar"
  tags:
    - administrative_templates_computer
    - start_menu_and_taskbar
  ansible.builtin.import_tasks:
    file: cis_18.8.x.yml
