---

- name: "19.7.5.1 | PATCH | Ensure Do not preserve zone information in file attachments is set to Disabled"
  when: win11cis_rule_19_7_5_1
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_19.7.5.1
    - preserve_zone_information
    - NIST800-171_3.4.2
    - NIST800-53R5_CM-6_b
  ansible.windows.win_regedit:
    path: HKU:\{{ item }}\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments
    name: SaveZoneInformation
    data: 2
    type: dword
  loop: "{{ discovered_hku_loaded_list }}"
  notify: Change_requires_reboot

- name: "19.7.5.2 | PATCH | Ensure Notify antivirus programs when opening attachments is set to Enabled"
  when: win11cis_rule_19_7_5_2
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_19.7.5.2
    - antivirus
    - NIST800-171_3.14.2
    - NIST800-171_3.14.4
    - NIST800-171_3.14.5
    - NIST800-53R5_SI-3
  ansible.windows.win_regedit:
    path: HKU:\{{ item }}\Software\Microsoft\Windows\Currentversion\Policies\Attachments
    name: ScanWithAntiVirus
    data: 3
    type: dword
  loop: "{{ discovered_hku_loaded_list }}"
  notify: Change_requires_reboot
