---

- name: "18.10.92.1.1 | PATCH | Ensure No auto-restart with logged on users for scheduled automatic updates installations is set to Disabled"
  when: win11cis_rule_18_10_92_1_1
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.1.1
    - legacy_policies
    - NIST800-171_3.11.2
    - NIST800-171_3.11.3
    - NIST800-171_3.14.1
    - NIST800-53R5_RA-5
    - NIST800-53R5_SI-2
    - NIST800-53R5_SI-2_2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au
    name: NoAutoRebootWithLoggedOnUsers
    data: 0
    type: dword

- name: "18.10.92.2.1 | PATCH | Ensure Configure Automatic Updates is set to Enabled"
  when: win11cis_rule_18_10_92_2_1
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.2.1
    - manage_end_user_experience
    - updates
    - NIST800-171_3.11.2
    - NIST800-171_3.11.3
    - NIST800-171_3.14.1
    - NIST800-53R5_RA-5
    - NIST800-53R5_SI-2
    - NIST800-53R5_SI-2_2
  block:
    - name: "18.10.92.2.1 | PATCH | Ensure Configure Automatic Updates is set to Enabled | Set Auto Update"
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au
        name: NoAutoUpdate
        data: 0
        type: dword

    - name: "18.10.92.2.1 | PATCH | Ensure Configure Automatic Updates is set to Enabled | Set Properties For Updates"
      when:
        - win11cis_au_options >= 2
        - win11cis_au_options <= 5
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au
        name: AUOptions
        data: "{{ win11cis_au_options }}"
        type: dword

    - name: "18.10.92.2.1 | AUDIT | Ensure Configure Automatic Updates is set to Enabled | Warning Message Bad Variable"
      when: win11cis_au_options < 2 or win11cis_au_options > 5
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid setting for win11cis_au_options. Please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "18.10.92.2.1 | AUDIT | Ensure Configure Automatic Updates is set to Enabled | Warning Count"
      when: win11cis_au_options < 2 or win11cis_au_options > 5
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '18.10.92.2.1'

- name: "18.10.92.2.2 | PATCH | Ensure 'Configure Automatic Updates: Scheduled install day' is set to '0 - Every day' "
  when:
    - win11cis_rule_18_10_92_2_2
    - win11cis_au_options == 4
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.2.2
    - manage_end_user_experience
    - updates
    - NIST800-171_3.11.2
    - NIST800-171_3.11.3
    - NIST800-171_3.14.1
    - NIST800-53R5_RA-5
    - NIST800-53R5_SI-2
    - NIST800-53R5_SI-2_2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Windowsupdate\Au
    name: ScheduledInstallDay
    data: 0
    type: dword

- name: "18.10.92.2.3 | PATCH | Ensure 'Enable features introduced via servicing that are off by default' is set to 'Disabled'"
  when: win11cis_rule_18_10_92_2_3
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.2.3
    - manage_end_user_experience
    - features
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: AllowTemporaryEnterpriseFeatureControl
    data: 0
    type: dword

- name: "18.10.92.2.4 | PATCH | Ensure 'Remove access to “Pause updates” feature' is set to 'Enabled'"
  when: win11cis_rule_18_10_92_2_4
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.2.4
    - manage_end_user_experience
    - updates
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: SetDisablePauseUXAccess
    data: 1
    type: dword

- name: "18.10.92.4.1 | PATCH | Ensure 'Manage preview builds' is set to 'Disabled'"
  when: win11cis_rule_18_10_92_4_1
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.4.1
    - manage_updates_offered_from_windows_update
    - preview
    - NIST800-171_3.4.8
    - NIST800-53R5_CM-10
    - NIST800-53R5_CM-7_5
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
    name: ManagePreviewBuildsPolicyValue
    data: 1
    type: dword

- name: "18.10.92.4.2 | PATCH | Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days'"
  when: win11cis_rule_18_10_92_4_2
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.4.2
    - manage_updates_offered_from_windows_update
    - preview
    - NIST800-171_3.11.2
    - NIST800-171_3.11.3
    - NIST800-171_3.14.1
    - NIST800-53R5_RA-5
    - NIST800-53R5_SI-2
    - NIST800-53R5_SI-2_2
  block:
    - name: "18.10.92.4.2 | PATCH | Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days' | DeferFeatureUpdates"
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
        name: DeferFeatureUpdates
        data: 1
        type: dword

    - name: "18.10.92.4.2 | PATCH | Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days' | DeferFeatureUpdatesPeriodInDays"
      when: win11cis_defer_feature_updates_period_in_days >= 180
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
        name: DeferFeatureUpdatesPeriodInDays
        data: "{{ win11cis_defer_feature_updates_period_in_days }}"
        type: dword

    - name: "18.10.92.4.2 | AUDIT | Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days' | Variable Warning"
      when: win11cis_defer_feature_updates_period_in_days < 180
      ansible.builtin.debug:
        msg:
          - "Warning!! You have an invalid number of days for win11cis_defer_feature_updates_period_in_days. Please read"
          - "the notes for the variable and make the necessary change to the variable to be in compliance."

    - name: "18.10.92.4.2 | AUDIT | Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days' | Warning Count"
      when: win11cis_defer_feature_updates_period_in_days < 180
      ansible.builtin.import_tasks:
        file: warning_facts.yml
      vars:
        warn_control_id: '18.10.92.4.2'

- name: "18.10.92.4.3 | PATCH | Ensure Select when Quality Updates are received is set to Enabled 0 days"
  when: win11cis_rule_18_10_92_4_3
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.4.3
    - manage_updates_offered_from_windows_update
    - updates
    - NIST800-171_3.11.2
    - NIST800-171_3.11.3
    - NIST800-171_3.14.1
    - NIST800-53R5_RA-5
    - NIST800-53R5_SI-2
    - NIST800-53R5_SI-2_2
  block:
    - name: "18.10.92.4.3 | PATCH | Ensure Select when Quality Updates are received is set to Enabled 0 days | DeferQualityUpdates"
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: DeferQualityUpdates
        data: 1
        type: dword

    - name: "18.10.92.4.3 | PATCH | Ensure Select when Quality Updates are received is set to Enabled 0 days | DeferQualityUpdatesPeriodInDays"
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
        name: DeferQualityUpdatesPeriodInDays
        data: 0
        type: dword

- name: "18.10.92.4.4 | PATCH | Ensure Enable optional updates is set to Disabled"
  when: win11cis_rule_18_10_92_4_4
  tags:
    - level1-corporate-enterprise-environment
    - patch
    - automated
    - rule_18.10.92.4.4
    - manage_updates_offered_from_windows_update
    - updates
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
    name: AllowOptionalContent
    data: 0
    type: dword
