---

- name: "18.10.75.1.1 | PATCH | Ensure 'Automatic Data Collection' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components
      name: CaptureThreatWindow
      data: 1
      type: dword
  when: win11cis_rule_18_10_75_1_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.75.1.1
      - enhanced_phishing_protection

- name: "18.10.75.1.2 | PATCH | Ensure 'Notify Malicious' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components
      name: NotifyMalicious
      data: 1
      type: dword
  when: win11cis_rule_18_10_75_1_2
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.75.1.2
      - enhanced_phishing_protection

- name: "18.10.75.1.3 | PATCH | Ensure 'Notify Password Reuse' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components
      name: NotifyPasswordReuse
      data: 1
      type: dword
  when: win11cis_rule_18_10_75_1_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.75.1.3
      - enhanced_phishing_protection

- name: "18.10.75.1.4 | PATCH | Ensure 'Notify Unsafe App' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components
      name: NotifyUnsafeApp
      data: 1
      type: dword
  when: win11cis_rule_18_10_75_1_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.75.1.4
      - enhanced_phishing_protection

- name: "18.10.75.1.5 | PATCH | Ensure 'Service Enabled' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components
      name: ServiceEnabled
      data: 1
      type: dword
  when: win11cis_rule_18_10_75_1_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.75.1.5
      - enhanced_phishing_protection

- name: "18.10.75.2.1 | PATCH | Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled: Warn and prevent bypass'"
  block:
      - name: "18.10.75.2.1 | PATCH | Ensure Configure Windows Defender SmartScreen is set to Enabled Warn and prevent bypass | EnableSmartScreen"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\System
            name: EnableSmartScreen
            data: 1
            type: dword

      - name: "18.10.75.2.1 | PATCH | Ensure Configure Windows Defender SmartScreen is set to Enabled Warn and prevent bypass | ShellSmartScreenLevel"
        ansible.windows.win_regedit:
            path: HKLM:\Software\Policies\Microsoft\Windows\System
            name: ShellSmartScreenLevel
            data: Block
            type: string
  when: win11cis_rule_18_10_75_2_1
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.75.2.1
      - explorer
