---

- name: "18.10.28.2 | PATCH | Ensure 'Turn off account-based insights, recent, favorite, and recommended files in File Explorer' is set to 'Enabled'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
      name: DisableGraphRecentItems
      data: 1
      type: dword
  when: win11cis_rule_18_10_28_2
  tags:
      - level2-high-security-sensitive-data-environment
      - patch
      - automated
      - rule_18.10.28.2

- name: "18.10.28.3 | PATCH | Ensure Turn off Data Execution Prevention for Explorer is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
      name: NoDataExecutionPrevention
      data: 0
      type: dword
  when: win11cis_rule_18_10_28_3
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.28.3
      - data_execution_prevention

- name: "18.10.28.4 | PATCH | Ensure Turn off heap termination on corruption is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
      name: NoHeapTerminationOnCorruption
      data: 0
      type: dword
  when: win11cis_rule_18_10_28_4
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.28.4
      - heap_termination

- name: "18.10.28.5 | PATCH | Ensure Turn off shell protocol protected mode is set to Disabled"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
      name: PreXPSP2ShellProtocolBehavior
      data: 0
      type: dword
  when: win11cis_rule_18_10_28_5
  tags:
      - level1-corporate-enterprise-environment
      - patch
      - automated
      - rule_18.10.28.5
      - shell
