---

- name: "SECTION | 18.10.3 | App Package Deployment"
  tags:
    - administrative_templates_computer
    - windows_components
    - app_package_deployment
  ansible.builtin.import_tasks:
    file: cis_18.10.3.x.yml

- name: "SECTION | 18.10.4 | App Privacy"
  tags:
    - administrative_templates_computer
    - windows_components
    - app_privacy
  ansible.builtin.import_tasks:
    file: cis_18.10.4.x.yml

- name: "SECTION | 18.10.5 | App Runtime"
  tags:
    - administrative_templates_computer
    - windows_components
    - app_runtime
  ansible.builtin.import_tasks:
    file: cis_18.10.5.x.yml

- name: "SECTION | 18.10.7 | Autoplay Policies"
  tags:
    - administrative_templates_computer
    - windows_components
    - autoplay_policies
  ansible.builtin.import_tasks:
    file: cis_18.10.7.x.yml

- name: "SECTION | 18.10.8 | Biometrics"
  tags:
    - administrative_templates_computer
    - windows_components
    - biometrics
  ansible.builtin.import_tasks:
    file: cis_18.10.8.x.yml

- name: "SECTION | 18.10.9 | Bitlocker Drive Encryption"
  tags:
    - administrative_templates_computer
    - windows_components
    - bitlocker_drive_encryption
  ansible.builtin.import_tasks:
    file: cis_18.10.9.x.yml

- name: "SECTION | 18.10.10 | Camera"
  tags:
    - administrative_templates_computer
    - windows_components
    - camera
  ansible.builtin.import_tasks:
    file: cis_18.10.10.x.yml

- name: "SECTION | 18.10.12 | Cloud Content"
  tags:
    - administrative_templates_computer
    - windows_components
    - cloud_content
  ansible.builtin.import_tasks:
    file: cis_18.10.12.x.yml

- name: "SECTION | 18.10.13 | Connect"
  tags:
    - administrative_templates_computer
    - windows_components
    - connect
  ansible.builtin.import_tasks:
    file: cis_18.10.13.x.yml

- name: "SECTION | 18.10.14 | Credential User Interface"
  tags:
    - administrative_templates_computer
    - windows_components
    - credential_user_interface
  ansible.builtin.import_tasks:
    file: cis_18.10.14.x.yml

- name: "SECTION | 18.10.15 | Data Collection And Preview Builds"
  tags:
    - administrative_templates_computer
    - windows_components
    - data_collection_and_preview_builds
  ansible.builtin.import_tasks:
    file: cis_18.10.15.x.yml

- name: "SECTION | 18.10.16 | Delivery Optimization"
  tags:
    - administrative_templates_computer
    - windows_components
    - delivery_optimization
  ansible.builtin.import_tasks:
    file: cis_18.10.16.x.yml

- name: "SECTION | 18.10.17 | Desktop App Installer"
  tags:
    - administrative_templates_computer
    - windows_components
    - desktop_app_installer
  ansible.builtin.import_tasks:
    file: cis_18.10.17.x.yml

- name: "SECTION | 18.10.25 | Event Log Service"
  tags:
    - administrative_templates_computer
    - windows_components
    - event_log_service
  ansible.builtin.import_tasks:
    file: cis_18.10.25.x.yml

- name: "SECTION | 18.10.28 | File Explorer (Formerly Windows Explorer)"
  tags:
    - administrative_templates_computer
    - windows_components
    - file_explorer
  ansible.builtin.import_tasks:
    file: cis_18.10.28.x.yml

- name: "SECTION | 18.10.36 | Location And Sensors"
  tags:
    - administrative_templates_computer
    - windows_components
    - location_and_sensors
  ansible.builtin.import_tasks:
    file: cis_18.10.36.x.yml

- name: "SECTION | 18.10.40 | Messaging"
  tags:
    - administrative_templates_computer
    - windows_components
    - messaging
  ansible.builtin.import_tasks:
    file: cis_18.10.40.x.yml

- name: "SECTION | 18.10.41 | Microsoft Account"
  tags:
    - administrative_templates_computer
    - windows_components
    - microsoft_account
  ansible.builtin.import_tasks:
    file: cis_18.10.41.x.yml

- name: "SECTION | 18.10.42 | Microsoft Defender Antivirus (formerly Windows Defender and Windows Defender Antivirus)"
  tags:
    - administrative_templates_computer
    - windows_components
    - microsoft_defender_antivirus
  ansible.builtin.import_tasks:
    file: cis_18.10.42.x.yml

- name: "SECTION | 18.10.43 | Microsoft Defender Application Guard (formerly Windows Defender Application Guard)"
  tags:
    - administrative_templates_computer
    - windows_components
    - microsoft_defender_application_guard
  ansible.builtin.import_tasks:
    file: cis_18.10.43.x.yml

- name: "SECTION | 18.10.49 | News And Interests"
  tags:
    - administrative_templates_computer
    - windows_components
    - news_and_interests
  ansible.builtin.import_tasks:
    file: cis_18.10.49.x.yml

- name: "SECTION | 18.10.50 | OneDrive (Formerly SkyDrive)"
  tags:
    - administrative_templates_computer
    - windows_components
    - onedrive
  ansible.builtin.import_tasks:
    file: cis_18.10.50.x.yml

- name: "SECTION | 18.10.55 | Push To Install"
  tags:
    - administrative_templates_computer
    - windows_components
    - push_to_install
  ansible.builtin.import_tasks:
    file: cis_18.10.55.x.yml

- name: "SECTION | 18.10.56 | Remote Desktop Services (formerly Terminal Services)"
  tags:
    - administrative_templates_computer
    - windows_components
    - remote_desktop_services
  ansible.builtin.import_tasks:
    file: cis_18.10.56.x.yml

- name: "SECTION | 18.10.57 | RSS Feeds"
  tags:
    - administrative_templates_computer
    - windows_components
    - rss_feeds
  ansible.builtin.import_tasks:
    file: cis_18.10.57.x.yml

- name: "SECTION | 18.10.58 | Search"
  tags:
    - administrative_templates_computer
    - windows_components
    - search
  ansible.builtin.import_tasks:
    file: cis_18.10.58.x.yml

- name: "SECTION | 18.10.62 | Software Protection Platform"
  tags:
    - administrative_templates_computer
    - windows_components
    - software_protection_platform
  ansible.builtin.import_tasks:
    file: cis_18.10.62.x.yml

- name: "SECTION | 18.10.65 | Store"
  tags:
    - administrative_templates_computer
    - windows_components
    - store
  ansible.builtin.import_tasks:
    file: cis_18.10.65.x.yml

- name: "SECTION | 18.10.71 | Widgets"
  tags:
    - administrative_templates_computer
    - windows_components
    - widgets
  ansible.builtin.import_tasks:
    file: cis_18.10.71.x.yml

- name: "SECTION | 18.10.75 | Windows Defender SmartScreen"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_defender_smartscreen
  ansible.builtin.import_tasks:
    file: cis_18.10.75.x.yml

- name: "SECTION | 18.10.77 | Windows Game Recording and Broadcasting"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_game_recording_and_broadcasting
  ansible.builtin.import_tasks:
    file: cis_18.10.77.x.yml

- name: "SECTION | 18.10.78 | Windows Hello for Business (formerly Microsoft Passport for Work)"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_hello_for_business
  ansible.builtin.import_tasks:
    file: cis_18.10.78.x.yml

- name: "SECTION | 18.10.79 | Windows Ink Workspace"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_ink_workspace
  ansible.builtin.import_tasks:
    file: cis_18.10.79.x.yml

- name: "SECTION | 18.10.80 | Windows Installer"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_installer
  ansible.builtin.import_tasks:
    file: cis_18.10.80.x.yml

- name: "SECTION | 18.10.81 | Windows Logon Options"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_logon_options
  ansible.builtin.import_tasks:
    file: cis_18.10.81.x.yml

- name: "SECTION | 18.10.86 | Windows Powershell"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_powershell
  ansible.builtin.import_tasks:
    file: cis_18.10.86.x.yml

- name: "SECTION | 18.10.88 | Windows Remote Management (WinRM)"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_remote_management
  ansible.builtin.import_tasks:
    file: cis_18.10.88.x.yml

- name: "SECTION | 18.10.89 | Windows Remote Shell"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_remote_shell
  ansible.builtin.import_tasks:
    file: cis_18.10.89.x.yml

- name: "SECTION | 18.10.90 | Windows Sandbox"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_sandbox
  ansible.builtin.import_tasks:
    file: cis_18.10.90.x.yml

- name: "SECTION | 18.10.91 | Windows Security (formerly Windows Defender Security Center)"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_security
  ansible.builtin.import_tasks:
    file: cis_18.10.91.x.yml

- name: "SECTION | 18.10.92 | Windows Update"
  tags:
    - administrative_templates_computer
    - windows_components
    - windows_update
  ansible.builtin.import_tasks:
    file: cis_18.10.92.x.yml
