---

- name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0."
  block:
      - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Verify Variable Not 0 or more then 5 warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of attempts set for win11cis_bad_login_lockout_count. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win11cis_bad_login_lockout_count > 5 or
              win11cis_bad_login_lockout_count == 0

      - name: "1.2.2 | AUDIT | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.2.2'
        when:
            - win11cis_bad_login_lockout_count > 5 or
              win11cis_bad_login_lockout_count == 0

      - name: "1.2.2 | PATCH | Ensure Account lockout threshold is set to 5 or fewer invalid logon attempt(s), but not 0. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: LockoutBadCount
            value: "{{ win11cis_bad_login_lockout_count }}"
        when:
            - win11cis_bad_login_lockout_count <= 5
            - win11cis_bad_login_lockout_count > 0
  when:
      - win11cis_rule_1_2_2
  tags:
      - level1-corporate-enterprise-environment
      - automated
      - patch
      - rule_1.2.2

# Speelman | added because of this error "Failed to import secedit.ini file from C:\\Users\\vagrant\\AppData\\Local\\Temp\\tmp81F3.tmp
- name: "1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes."
  block:
      - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of minutes set for win11cis_account_lockout_duration please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when: win11cis_account_lockout_duration < 15

      - name: "1.2.1 | AUDIT | Ensure Account lockout duration is set to 15 or more minutes. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.2.1'
        when: win11cis_account_lockout_duration < 15

      - name: "1.2.1 | PATCH | Ensure Account lockout duration is set to 15 or more minutes. | Set Variable"
        community.windows.win_security_policy:
            section: System Access
            key: LockoutDuration
            value: "{{ win11cis_account_lockout_duration }}"
        when: win11cis_account_lockout_duration >= 15
  when:
      - win11cis_rule_1_2_1
  tags:
      - level1-corporate-enterprise-environment
      - automated
      - patch
      - rule_1.2.1

- name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes."
  block:
      - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Verify variable set to 15 or more minutes warning."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have an invalid number of minutes set for win11cis_account_lockout_counter_reset. Please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win11cis_account_lockout_counter_reset > win11cis_account_lockout_duration or
              win11cis_account_lockout_counter_reset < 15

      - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set warning count."
        ansible.builtin.import_tasks:
            file: warning_facts.yml
        vars:
            warn_control_id: '1.2.4'
        when:
            - win11cis_account_lockout_counter_reset > win11cis_account_lockout_duration or
              win11cis_account_lockout_counter_reset < 15

      - name: "1.2.4 | PATCH | Ensure Reset account lockout counter after is set to 15 or more minutes. | Set Variable."
        community.windows.win_security_policy:
            section: System Access
            key: ResetLockoutCount
            value: "{{ win11cis_account_lockout_counter_reset }}"
        when:
            - win11cis_account_lockout_counter_reset >= 15
            - win11cis_account_lockout_counter_reset <= win11cis_account_lockout_duration
  when:
      - win11cis_rule_1_2_4
  tags:
      - level1-corporate-enterprise-environment
      - automated
      - patch
      - rule_1.2.4
