---

- name: "SECTION | 1.1 | Password Policy"
  tags:
    - account_policies
    - password_policy
  ansible.builtin.import_tasks:
    file: cis_1.1.x.yml

- name: "SECTION | 1.2 | Account Lockout Policy"
  tags:
    - account_policies
    - account_lockout_policy
  ansible.builtin.import_tasks:
    file: cis_1.2.x.yml
